ALTER TABLE public.user_preferences
  ADD COLUMN IF NOT EXISTS hide_completed_task_objectives BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_all_filter BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_available_filter BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_locked_filter BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_completed_filter BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_failed_filter BOOLEAN DEFAULT TRUE;
